[app.spotify.api]
url = "https://api.spotify.com/"

[app.spotify.api.paths]
currently-playing = "v1/me/player/currently-playing"
my-playlists = "v1/me/playlists"
library = "v1/me/library"
playlist-items = "v1/playlists/{id}/items"
next-track = "v1/me/player/next"

[app.spotify.auth]
auth_uri = "https://accounts.spotify.com/authorize"
token_uri = "https://accounts.spotify.com/api/token"
redirect_uri = "http://127.0.0.1:8888/callback"
scopes = [
    "user-read-currently-playing",
    "user-read-playback-state",
    "user-modify-playback-state",
    "playlist-read-private",
    "playlist-modify-private",
    "playlist-modify-public",
    "user-library-read",
    "user-library-modify",
]

[hotkeys]
filter = "Ctrl+Alt+D"
pass = "Ctrl+Alt+L"
